version: '3.7'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
     - "5432:5432"
    
  rails:
    build: ./ 
    command: "./bin/rails server -b 0.0.0.0"

    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    
    volumes:
      - .:/docker/spacemission  # add our local code to dockerfile
    depends_on:
      - db  # add all dependant container
    ports:
     - "3000:3000"

volumes:
  postgres_data: {}
  app-storage: {}